name: Check Merge Safety

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Merge Safety
    runs-on: ubuntu-latest
    steps:
      - uses: ExpediaGroup/github-helpers@check-merge-safety
        with:
          helper: check-merge-safety
          paths: |
            packages/package-a
            packages/package-b
          override_filter_paths: |
            package.json
          github_token: ${{ secrets.GITHUB_TOKEN }}
