name: Check Merge Safety

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Merge Safety
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: actions/setup-pnpm@v2
        run_install: true
        with:
          version: 7.9.0

      - uses: ExpediaGroup/github-helpers@simplify-check-merge-safety
        with:
          helper: check-merge-safety
          paths: |
            packages/package-a
            packages/package-b
          override_filter_paths: |
            package.json
          github_token: ${{ secrets.GITHUB_TOKEN }}
